### ISSUE TITLE
No souce link 

### ISSUE THREAD

**Issue by ntimo** [BukkitPE/Multicraft#1]
Hello,

I saw your Jenkins server is up. Could you please update the multicraft conf file with the download url of the jar? Thank you :)

**Comment by xZeroMCPE** [comment]
Added!

**Comment by ntimo** [comment]
Hi, it seems like the link you added does not work? I get an 404 forbidden error.

**Comment by xZeroMCPE** [comment]
Jenkins been down for a few days. I forgot how i'd setup jenkins to make builds from git.

**Comment by ntimo** [comment]
So, what does it mean? Will Jekins be up some time soon?

**Comment by xZeroMCPE** [comment]
Yes it will, just need to somehow learn _again_ how to setup the jenkins. :+1:

**Comment by xZeroMCPE** [comment]
@ntimo  Jenkins is up! and it's currently working! :)
